### ISSUE TITLE
notes for bots

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/bot#43]
So in case you aren't testing a bot just yet but you want to leave a note so you or another moderator could see it in the feature.

How'd it work is simple. A moderator that noticed an issue would run `del,addnote <bot> <note>`  which would add a note to that bot, and later, when (another) moderator is testing the given bot they can execute `del,notes <bot>` to see all the notes added and a moderator who added the notes.

In case that note is useless a moderator could run `del,removenote <bot> <noteid>` which would obviously remove the note from the provided bot.

I haven't mentioned yet, but - this would only be available for bots that haven't been approved yet and usable only by moderators/assistants/administrators. (All the notes would automatically get removed whenever the bot is approved)

**Comment by advaith1** [comment]
you could just make a channel and send the notes there?

**Comment by TheMoksej** [comment]
I mean yes, but notes are better imo :)

**Comment by TheMoksej** [comment]
I also could work on it as it's almost the same as the todo lists on my bot. I'd just fuck up with database checks, etc..
